import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module, { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const ts = require('typescript');
const filename = fileURLToPath(new URL('./dialog-focus.ts', import.meta.url));
const compiled = new Module(filename);
compiled.filename = filename;
compiled.paths = Module._nodeModulePaths(fileURLToPath(new URL('.', import.meta.url)));
compiled._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, filename);
const { dialogFocusAction } = compiled.exports;
assert.equal(dialogFocusAction('Escape', false, false, false, true), 'dismiss');
assert.equal(dialogFocusAction('Tab', true, true, false, true), 'last');
assert.equal(dialogFocusAction('Tab', false, false, true, true), 'first');
assert.equal(dialogFocusAction('Tab', false, true, false, true), 'none');
assert.equal(dialogFocusAction('Tab', true, false, true, true), 'none');
assert.equal(dialogFocusAction('Tab', false, false, false, false), 'first');
assert.equal(dialogFocusAction('Tab', true, false, false, false), 'last');
assert.equal(dialogFocusAction('Enter', false, false, false, true), 'none');
assert.equal(dialogFocusAction('Tab', true, true, true, true), 'last');
assert.equal(dialogFocusAction('Tab', false, true, true, true), 'first');
console.log('10 modal keyboard-policy assertions passed. Live focus/interaction QA remains separate.');
