---
ID: "2239333c-ce30-54c1-ab7f-e9f7fa313fdf"
Parent: "d0495e26-94c5-5b92-b97d-50ef4fff1c49"
Template: "d0495e26-94c5-5b92-b97d-50ef4fff1c49"
Path: "/sitecore/templates/Project/Allianz Life/Components/AllianzSearch/__Standard Values"
