---
ID: "066ef8c6-052f-592b-9718-4d92d43c44b8"
Parent: "22dbc0a2-6ff5-5a9a-a70b-b9e79a6ea1b6"
Template: "22dbc0a2-6ff5-5a9a-a70b-b9e79a6ea1b6"
Path: "/sitecore/templates/Project/Allianz Life/Components/AllianzLegacySidebar/__Standard Values"
