---
ID: "6c4a08ee-ea7a-5d4e-9f06-49ee4805c5dc"
Parent: "eff5b538-3abe-5b3c-9e97-fd5ef78f5213"
Template: "eff5b538-3abe-5b3c-9e97-fd5ef78f5213"
Path: "/sitecore/templates/Project/Allianz Life/Pages/AllianzPage/__Standard Values"
