---
ID: "c3eea108-c496-5e42-be9b-7feebafe8003"
Parent: "d44a6ec4-6cbb-5409-86d9-a3a3f3bd8f0b"
Template: "d44a6ec4-6cbb-5409-86d9-a3a3f3bd8f0b"
Path: "/sitecore/templates/Project/Allianz Life/Components/AllianzFooter/__Standard Values"
