import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module, { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const ts = require('typescript');
const filename = fileURLToPath(new URL('./allianz-metadata.ts', import.meta.url));
const compiled = new Module(filename);
compiled.filename = filename;
compiled.paths = Module._nodeModulePaths(fileURLToPath(new URL('.', import.meta.url)));
compiled._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, filename);
const { allianzMetadata } = compiled.exports;
const native = allianzMetadata({ pageTitle: { value: ' Native title ' }, metaDescription: { value: 'Native description' }, Title: { value: 'Scaffold title' }, metadataDescription: { value: 'Scaffold description' } });
assert.equal(native.title, 'Native title');
assert.equal(native.description, 'Native description');
assert.equal(native.openGraphTitle, 'Native title');
assert.equal(native.openGraphDescription, 'Native description');
assert.equal(allianzMetadata({ Title: { value: 'Fixture title' } }).title, 'Fixture title');
assert.equal(allianzMetadata({ pageTitle: { value: ' ' }, Title: { value: 'Scaffold title' } }).title, 'Scaffold title');
assert.equal(allianzMetadata({ metaDescription: { value: 'SEO' }, ogDescription: { value: 'Social' } }).openGraphDescription, 'Social');
assert.deepEqual(allianzMetadata(), { title: 'Page', description: '', openGraphTitle: 'Page', openGraphDescription: '' });
console.log('8 native-schema metadata assertions passed.');
