import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module, { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const ts = require('typescript');
const filename = fileURLToPath(new URL('./collection-completeness.ts', import.meta.url));
const compiled = new Module(filename);
compiled.filename = filename;
compiled.paths = Module._nodeModulePaths(fileURLToPath(new URL('.', import.meta.url)));
compiled._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, filename);
const { collectionsComplete } = compiled.exports;
assert.equal(collectionsComplete({ children: { results: [{ id: '1' }] } }), true);
assert.equal(collectionsComplete({ children: { results: [{ id: '1' }] } }, true), false);
assert.equal(collectionsComplete({ children: { total: 1, pageInfo: { hasNext: false }, results: [{ id: '1' }] } }, true), true);
assert.equal(collectionsComplete({ children: { total: 2, pageInfo: { hasNext: true }, results: [{ id: '1' }] } }), false);
assert.equal(collectionsComplete({ children: { total: 2, pageInfo: { hasNext: false }, results: [{ id: '1' }] } }), false);
assert.equal(collectionsComplete({ children: { total: 1, pageInfo: { hasNext: false } } }), false);
assert.equal(collectionsComplete({ children: { total: 0, pageInfo: { hasNext: false } } }, true), true);
assert.equal(collectionsComplete({ nav: { targetItems: [{ children: { total: 2, pageInfo: { hasNext: true }, results: [] } }] } }), false);
const fixtures = JSON.parse(fs.readFileSync(new URL('../../content/native-content.json', import.meta.url), 'utf8'));
assert.equal(collectionsComplete(fixtures), true);
console.log('9 native collection-completeness assertions passed; all 357 fixture routes retained.');
