import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module, { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const ts = require('typescript');
const filename = fileURLToPath(new URL('./allianz-fields.ts', import.meta.url));
const compiled = new Module(filename);
compiled.filename = filename;
compiled.paths = Module._nodeModulePaths(fileURLToPath(new URL('.', import.meta.url)));
compiled._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }).outputText, filename);
const { safeLink } = compiled.exports;
const href = (value) => safeLink({ value: { href: value } }).value.href;
assert.equal(href('/what-we-offer/annuities'), '/what-we-offer/annuities');
assert.equal(href('/rates'), '#service-unavailable');
assert.equal(href('/for-financial-professionals/advisory-solutions'), '#service-unavailable');
assert.equal(href('/what-we-offer/life-insurance/the-underwriting-process'), '#service-unavailable');
assert.equal(href('/about/newsroom/_local/missing'), '#service-unavailable');
assert.equal(href('/for-financial-professionals/resources/4-ways-to-help-clients-fight-inflation'), '/for-financial-professionals/resources/4-ways-to-help-clients-fight-inflation');
assert.equal(href('/allianz-assets/source.pdf'), '/allianz-assets/source.pdf');
assert.equal(href('https://www.allianzlife.com/login'), '#service-unavailable');
assert.equal(href('https://external.example.invalid/'), '#service-unavailable');
assert.equal(href('#section'), '#section');
console.log('10 captured-route and safe-link assertions passed. Unrecovered source routes remain local service states.');
