---
ID: "f54e1f4e-0947-5103-a8db-ea595fad3990"
Parent: "2d97ae6b-40da-5817-bfd2-a57b12b55e2c"
Template: "2d97ae6b-40da-5817-bfd2-a57b12b55e2c"
Path: "/sitecore/templates/Project/Allianz Life/Components/AllianzRateSnapshot/__Standard Values"
