---
ID: "bafd845d-07eb-529d-bade-f4ee76b9dffa"
Parent: "8c5f1968-5f12-51d6-a854-fd534d5667d7"
Template: "8c5f1968-5f12-51d6-a854-fd534d5667d7"
Path: "/sitecore/templates/Project/Allianz Life/Components/AllianzLegacyRichText/__Standard Values"
